add fix_path plugin
frej/fast-export pull request #241
Opened 2020-09-09 08:07 UTC by bueli

This plugin sanitizes pathnames containing // (double slash) which will trigger [Empty path component found in input](https://github.com/frej/fast-export/issues/240) issue

2020-09-09 08:22 UTC, frej commented on plugins/fix_path/__init__.py
> +    # file_data = {'filename':filename,'file_ctx':file_ctx,'d':d}
Why add commented out code?

2020-09-09 08:36 UTC, frej requested changes
Please take a look at [what is a good commit message](https://chris.beams.io/posts/git-commit/) and amend your message accordingly. Make sure the subject starts with a capital letter and provide at least a one sentence description about what the plugin does in the body.

2020-09-09 08:36 UTC, frej commented on plugins/fix_path/__init__.py
> +        if filename and '//' in filename:
Why do this conditionally? The filename cannot be empty. Also, why scan the string twice?

2020-09-09 08:36 UTC, frej commented on plugins/fix_path/README.md
> +pathnames in hg repositories can be of the form /folder//subfolder/...
Sentences start with a capital letter

2020-09-09 08:36 UTC, frej commented on plugins/fix_path/__init__.py
> +    # file_data = {'filename':filename,'file_ctx':file_ctx,'d':d}
Don't add commented out code

2020-09-09 09:12 UTC, bueli commented
Reduced code and fixed commit message as you requested

2020-09-09 09:44 UTC, frej requested changes
Please squash your commits, there is no reason to preserve the development history of this small change for eternity.

Also make sure that the body of the commit message is wrapped at, at most 80, chars. The [previous linked](https://chris.beams.io/posts/git-commit/) recommends around 72.

Request a re-review when done.

2020-09-09 09:44 UTC, frej commented on plugins/fix_path/__init__.py
> +        if '//' in filename:
You have not answered the question of why you scan the string twice. As far as I can tell the `if '//' in filename` is completely redundant. Am I missing something?

2020-09-09 12:40 UTC, frej commented on plugins/fix_path/__init__.py
> +        if filename and '//' in filename:
Forget the comment about compiling the regexp, I read the code hastily, sorry.

2020-09-09 14:21 UTC, bueli commented
Hi Frej

Will squash soon.

I think your quality goals are very appropriate for production code.
But here we are in a deserted corner of an auxiliary tool ...
Why do you spend and demand so much effort?

You almost lost me, but now i want to understand where the energy is coming from ...

Cheers,
bue

> Am 09.09.2020 um 14:41 schrieb Frej Drejhammar <notifications@github.com>:
> 
> ﻿
> @frej commented on this pull request.
> 
> In plugins/fix_path/__init__.py:
> 
> > @@ -0,0 +1,12 @@
> +def build_filter(args):
> +    return Filter(args)
> +
> +class Filter:
> +    def __init__(self, args):
> +        i = 1
> +
> +    # file_data = {'filename':filename,'file_ctx':file_ctx,'d':d}
> +    def file_data_filter(self, file_data):
> +        filename = file_data['filename']
> +        if filename and '//' in filename:
> Forget the comment about compiling the regexp, I read the code hastily, sorry.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-09-09 15:49 UTC, frej commented
> But here we are in a deserted corner of an auxiliary tool ... Why do you spend and demand so much effort? You almost lost me, but now i want to understand where the energy is coming from

It's to minimize the maintenance effort, the clearer the patches, the simpler it is to maintain as I can figure out what a change is supposed to be doing. This is a real time saver, as with the declining popularity of Mercurial, I expect the frequency of maintenance actions to become more and more infrequent. The less time I have to spend to remember how something works, the happier I am.

As a maintainer, merging code is always a risk, if I merge a sloppy looking patch, will I have to maintain it in the future, are there hidden bugs? A sloppy looking patch does not really inspire confidence in the quality of the code, especially if the effort to make it "right" in the first place would have been minimal and only would have required a read-through on part of the contributor. Also the willingness to respond to review suggestions and questions is, I have found, a pretty good indication if the contributor will help me if unforeseen problems show up after the merge.

2020-09-10 18:58 UTC, frej commented
For the third time, why do you check if `//` occurs in the string before running `filename.replace("//", "/")`, instead of running `replace()` directly? Checking the Python implementation there is no performance benefit from it, you'll end up scanning the string twice when the pattern `//` is in the string.

2021-01-10 14:27 UTC, frej commented
No response to review comments in more than 90 days, closing without prejudice for inactivity.

2021-01-10 14:27 UTC, closed without merging